version: "3"
services:
  lif-backend:
    container_name: lif-backend
    image: gokris165/lif:back-latest
    ports:
      - 8080:8080
    networks:
      - lif
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://24.144.83.210:4000/let_it_fly
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: f23cs160frankbutt

  lif-frontend:
    container_name: lif-frontend
    image: gokris165/lif:front-latest
    ports:
      - 3000:3000
    networks:
      - lif
    depends_on:
      - lif-backend

networks:
  lif:
    driver: bridge
